# Generated by Django 5.1.1 on 2024-10-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Farmers_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Product_categories',
        ),
    ]
