# Generated by Django 5.1.1 on 2024-10-21 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_farmers_name_category_name_and_more'),
        ('LocalFarmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='categories',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocalFarmers.farmer')),
            ],
        ),
    ]
